### ISSUE TITLE
git-resource-model-1.0.1.jar not working on Rundeck 3.3.0

### ISSUE THREAD

**Issue by drodriguez-rundeck** [rundeck-plugins/git-resource-model#4]
Hi, looks like the git-resource-model-1.0.1.jar plugin is trying to import some class from old log4j logger and throws the following exceptions:

[2020-07-18T02:25:55,196] ERROR common.ProjectNodeSupport - Failed loading resource model source #2 in project xx, skipping: java.lang.NoClassDefFoundError: org/apache/log4j/Logger
Caused by: java.lang.NoClassDefFoundError: org/apache/log4j/Logger
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger

![git_resource_model_error](https://user-images.githubusercontent.com/48293178/87843014-d7ca1100-c87e-11ea-97b0-9209b7795ac9.jpg)

Steps to reproduce:
Copy  git-resource-model-1.0.1.jar into libext and configure a project to retrieve nodes from git.

**Comment by ltamaster** [comment]
Done 
https://github.com/rundeck-plugins/git-resource-model/pull/5
